name: Auto assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    permissions:
      contents: read
    uses: devops-ia/.github/.github/workflows/auto-assign.yaml@bcf48ba70f79f6f494b1831d1a5b992e474091d8
    with:
      teams: devops-ia
    secrets:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
